// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wite.go:

func Initialize(CityName string) City {
	school := NewSchool()
	city := NewCity(school, CityName)
	return city
}
